# Makefile: Description
#
# Copyright: (c) 2018-2025 Jacco van Schaik (jacco@jaccovanschaik.net)
# Created:   2018-11-18
# Version:   $Id: Makefile 4 2022-11-25 20:39:32Z jacco $
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.


INTO = into.o

CFLAGS = -g

INSTALL_BIN = $(HOME)/bin

into: $(INTO)
	$(CC) $(CFLAGS) -o into $(INTO)

update:
	git stash push
	git pull
	-git stash pop
	make install

clean:
	rm -f *.o into core into.tgz

into.tgz: clean
	tar cvf - `ls | grep -v into.tgz` | gzip > into.tgz

install: into
	if [ ! -d $(INSTALL_BIN) ]; then mkdir -p $(INSTALL_BIN); fi
	cp into $(INSTALL_BIN)

# Dependencies - generated by deps on Sun Nov 18 14:26:43 CET 2018

into.o: into.c 
