# Makefile: Description
#
# Copyright: (c) 2018 Jacco van Schaik (jacco@jaccovanschaik.net)
# Created:   2018-11-18
# Version:   $Id: Makefile 1 2018-11-18 18:14:20Z jacco $
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.


INTO = into.o

CFLAGS = -g

into: $(INTO)
	$(CC) $(CFLAGS) -o into $(INTO)

clean:
	rm -f *.o into core into.tgz

into.tgz: clean
	tar cvf - `ls | grep -v into.tgz` | gzip > into.tgz

install: into
	if [ ! -d $(INSTALL_BIN) ]; then mkdir -p $(INSTALL_BIN); fi
	cp into $(INSTALL_BIN)

# Dependencies - generated by deps on Sun Nov 18 14:26:43 CET 2018

into.o: into.c 
